import {
  FaSignOutAlt,
  FaTachometerAlt,
  FaBook,
  FaChartLine,
  FaUsers,
  FaPencilAlt,
  FaMarker,
  FaChevronLeft,
  FaChevronRight,
  FaBookOpen,
  FaListUl,
  FaCheckCircle,
  FaCalendarAlt,
  FaSignal,
  FaEllipsisH,
  FaClipboardCheck,
  FaListOl,
  FaBolt,
  FaLayerGroup,
  FaUser,
  FaPenNib,
  FaClipboardList,
  FaMicrophone,
  FaMedal,
  FaPlay,
  FaRedoAlt,
  FaCommentDots,
  FaPlus,
  FaSun,
  FaMoon,
  FaFire,
  FaInfoCircle,
  FaTimes,
  FaExclamationCircle
} from 'react-icons/fa';

const Icon = {
  SignOut: FaSignOutAlt,
  Dashboard: FaTachometerAlt,
  Book: FaBook,
  ChartLine: FaChartLine,
  Users: FaUsers,
  Practice: FaPencilAlt,
  Review: FaMarker,
  ChevronLeft: FaChevronLeft,
  ChevronRight: FaChevronRight,
  BookOpen: FaBookOpen,
  List: FaListUl,
  CheckCircle: FaCheckCircle,
  Calendar: FaCalendarAlt,
  Signal: FaSignal,
  Ellipsis: FaEllipsisH,
  ClipboardCheck: FaClipboardCheck,
  ListOl: FaListOl,
  Bolt: FaBolt,
  LayerGroup: FaLayerGroup,
  User: FaUser,
  PenNib: FaPenNib,
  ClipboardList: FaClipboardList,
  Microphone: FaMicrophone,
  Medal: FaMedal,
  Play: FaPlay,
  Redo: FaRedoAlt,
  CommentDots: FaCommentDots,
  Plus: FaPlus,
  Sun: FaSun,
  Moon: FaMoon,
  Fire: FaFire,
  Info: FaInfoCircle,
  X: FaTimes,
  AlertCircle: FaExclamationCircle
};

export default Icon;
